# Generated by Django 5.1.2 on 2024-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sch_s_date', models.DateField()),
                ('sch_f_date', models.DateField()),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('s_date', models.DateField()),
                ('f_date', models.DateField()),
                ('ot_prev', models.IntegerField()),
                ('ot_corr', models.IntegerField()),
                ('ot_prev_exe', models.IntegerField()),
                ('ot_corr_exe', models.IntegerField()),
            ],
        ),
    ]
