# Generated by Django 5.1.2 on 2024-10-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paradas',
            new_name='Parada',
        ),
    ]
