# Generated by Django 5.1.2 on 2024-10-29 16:02

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_paradas_parada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='status',
            field=models.CharField(choices=[('PL', 'En planificación'), ('PR', 'Programada'), ('GC', 'Gestión de compras'), ('EJ', 'En ejecución'), ('FN', 'Finalizada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(max_length=7, validators=[gestion.models.week_test]),
        ),
    ]
